apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.global-static-ip-name: guestbook-ip
  labels:
    app: guestbook
spec:
  backend:
    serviceName: guestbook-frontend-prod
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /entries
            backend:
              serviceName: guestbook-backend-prod
              servicePort: 8080
    - host: staging.guestbook.ernsthaagsman.com
      http:
        paths:
          - backend:
              serviceName: guestbook-frontend-staging
              servicePort: 80
          - path: /entries
            backend:
              serviceName: guestbook-backend-staging
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-backend-prod
  labels:
    app: guestbook
    layer: backend
    environment: prod
spec:
  type: NodePort
  selector:
    app: guestbook
    layer: backend
    environment: prod
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend-prod
  labels:
    app: guestbook
    layer: frontend
    environment: prod
spec:
  type: NodePort
  selector:
    app: guestbook
    layer: frontend
    environment: prod
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-backend-staging
  labels:
    app: guestbook
    layer: backend
    environment: staging
spec:
  type: NodePort
  selector:
    app: guestbook
    layer: backend
    environment: staging
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend-staging
  labels:
    app: guestbook
    layer: frontend
    environment: staging
spec:
  type: NodePort
  selector:
    app: guestbook
    layer: frontend
    environment: staging
  ports:
    - port: 80
      targetPort: 80
