apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guestbook-backend
  labels:
    app: guestbook
    layer: backend
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guestbook
        layer: backend
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcs-key
      containers:
        - name: guestbook-backend
          image: us.gcr.io/teamcitytest-166414/guestbook:pre1
          ports:
            - containerPort: 8080
          readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /entries
              port: 8080
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: gcp,postgres
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: GUESTBOOK_GCP_GCSBUCKET
              value: jb-gcp-guestbook
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: dbsettings
                  key: url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dbsettings
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsettings
                  key: password
