apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook
  annotations:
    kubernetes.io/ingress.global-static-ip-name: guestbook-ip
  labels:
    app: guestbook
spec:
  backend:
    serviceName: guestbook-frontend
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /entries
            backend:
              serviceName: guestbook-backend
              servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-backend
  labels:
    app: guestbook
    layer: backend
spec:
  type: NodePort
  selector:
    app: guestbook
    layer: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  labels:
    app: guestbook
    layer: frontend
spec:
  type: NodePort
  selector:
    app: guestbook
    layer: frontend
  ports:
    - port: 80
      targetPort: 80
