apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: guestbook-backend
  labels:
    app: backend
spec:
  replicas: 3
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: guestbook-backend
          image: us.gcr.io/ernsthaagsman-209012/guestbook:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            periodSeconds: 5
            httpGet:
              path: /entries
              port: 8080